### ISSUE TITLE
Convert to UICollectionView

### ISSUE THREAD

**Issue by twodayslate** [broha22/CSwitcher#1]
`UICollectionView`, from the [Apple Documentation](https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/CollectionViewPGforIOS/Introduction/Introduction.html), is a way to present an ordered set of data items using a flexible and changeable layout.

It would allow the rows to [automatically adjust](http://stackoverflow.com/a/16190291) when Applications are deleted. A custom `UICollectionViewFlowLayout` would even allow for easy switching between a single row or double row layout. 
### Tutorials and more information
- http://adoptioncurve.net/archives/2012/09/a-simple-uicollectionview-tutorial/
- http://code.tutsplus.com/tutorials/a-springboard-like-layout-with-the-uicollectionview-class--mobile-13426
- http://developer.xamarin.com/guides/ios/user_interface/introduction_to_collection_views/ 
- http://nshipster.com/uicollectionview/

**Comment by broha22** [comment]
Used as of latest commit
